spring.application.name=ms-cuentas

spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
