spring.application.name=bff-web

spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.msCuentas.sliding-window-size=5
resilience4j.circuitbreaker.instances.msCuentas.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.msCuentas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.msCuentas.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.msCuentas.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.msCuentas.ignore-exceptions=com.bancoxyz.bank_batch_system.common.exception.CuentaNoEncontradaException,com.bancoxyz.bank_batch_system.common.exception.FondosInsuficientesException
resilience4j.timelimiter.instances.msCuentas.timeout-duration=3s

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=bancoxyz123
server.ssl.key-alias=bankxyz
