bff.apikey=web-2024-xyz-key
ms.cuentas.base-url=http://localhost:8090

# OAuth2 Resource Server (JWT emitido por auth-server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
